name: Update Tools Index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd

      - name: List Files in Root (Debug Output)
        run: ls -al

      - name: List Files
        id: list_files
        run: |
          FILES=$(ls -F | grep -v '/$') # List files, exclude directories
          echo "files_output<<EOF" >> "$GITHUB_OUTPUT"
          echo "$FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "File list output for debugging:"
          echo "$FILES"

      - name: Generate HTML List and Update Index
        run: |
          set -x # Enable shell debugging
          FILE_LIST="${{ steps.list_files.outputs.files_output }}"
          echo "FILE_LIST content (raw):"
          echo "$FILE_LIST" | cat -vET # Show non-printing chars

          HTML_LIST=""
          IFS=$'\n' read -r -d '' -a FILES_ARRAY <<< "$FILE_LIST"
          echo "FILES_ARRAY length: ${#FILES_ARRAY[@]}"

          for file in "${FILES_ARRAY[@]}"; do
            echo "Processing file: '$file'"
            if [[ "$file" != "index.html" && "$file" != ".github" ]]; then
              FILENAME=$(basename "$file")
              HTML_LIST+="<li><a href=\"./$FILENAME\">$FILENAME</a></li>"
              echo "  Added to HTML_LIST: $FILENAME"
            else
              echo "  Skipping: $file"
            fi
          done

          echo "HTML_LIST content:"
          echo "$HTML_LIST"

          # Replace placeholder in index.html with the generated list
          sed -i "s|<!-- TOOL_LIST_HERE -->|$HTML_LIST|" index.html || true # Added || true for error robustness
          echo "index.html after TOOL_LIST_HERE replacement:"
          cat index.html

          # Update title tag
          sed -i "s|<title>CODEV.ID \\| Jasa Buat Website Professional #1</title>|<title>Tools</title>|" index.html || true # Added || true for error robustness
          echo "index.html after title replacement:"
          cat index.html
          set +x # Disable shell debugging

      - name: Commit and Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push updated index.html
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add index.html
          git commit -m "feat: Update tools index.html with file list"
          git push origin main
