name: Generate index.md (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

permissions: # Explicitly grant write permission
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or any Python 3 version

      - name: Generate index.md content with Python
        run: |
          python <<EOF
          import os

          html_files = [f for f in os.listdir('.') if f.endswith('.html') and f != 'index.html']
          markdown_list = ""

          if not html_files:
              markdown_list = "- No tools available yet."
          else:
              for filename in html_files:
                  tool_name = filename[:-5].replace('-', '_').upper() # Remove .html, format title
                  markdown_list += f"- [{tool_name}]({filename}) - Description for {filename}\\n"

          index_md_content = f"# Tools Directory\\n\\nThis is a directory of tools hosted on this subdomain. Click on the links below to access them.\\n\\n## Available Tools:\\n{markdown_list}"

          with open("index.md", "w") as f:
              f.write(index_md_content)

          print("index.md content:")
          print(index_md_content)
          EOF

      - name: Commit and Push index.md (Commands)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add index.md
          git commit -m "feat: Update index.md with HTML file list (Python)"
          git push origin main
