name: Generate index.md

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List HTML Files
        id: list_html_files
        run: |
          HTML_FILES=$(find . -maxdepth 1 -name "*.html" -not -name "index.html" -print)
          echo "html_file_list<<EOF" >> "$GITHUB_OUTPUT"
          echo "$HTML_FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "HTML Files found (debug):"
          echo "$HTML_FILES"

      - name: Generate index.md content
        run: |
          HTML_FILE_LIST="${{ steps.list_html_files.outputs.html_file_list }}"
          MARKDOWN_LIST=""
          IFS=$'\n' read -r -d '' -a HTML_FILES_ARRAY <<< "$HTML_FILE_LIST"
          if [[ ${#HTML_FILES_ARRAY[@]} -eq 0 ]]; then
            MARKDOWN_LIST="- No tools available yet."
          else
            for file in "${HTML_FILES_ARRAY[@]}"; do
              FILENAME=$(basename "$file")
              TOOL_NAME="${FILENAME%.html}" # Remove .html extension for title
              TOOL_NAME="${TOOL_NAME//-/_}" # Replace hyphens with underscores for title (optional)
              TOOL_NAME="${TOOL_NAME^^}"     # Convert to uppercase (optional)
              MARKDOWN_LIST+="- [$TOOL_NAME]($FILENAME) - Description for $FILENAME\n"
            done
          fi


          echo "index.md content:"
          echo "$MARKDOWN_LIST"

          echo "# Tools Directory\n\nThis is a directory of tools hosted on this subdomain. Click on the links below to access them.\n\n## Available Tools:\n$MARKDOWN_LIST" > index.md


      - name: Commit and Push index.md
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push index.md
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add index.md
          git commit -m "feat: Update index.md with HTML file list"
          git push origin main
