name: Update Tools Index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd

      - name: List Files in Root (Debug Output)
        run: ls -al

      - name: List Files
        id: list_files
        run: |
          FILES=$(ls -F | grep -v '/$') # List files, exclude directories
          echo "files_output<<EOF" >> "$GITHUB_OUTPUT"
          echo "$FILES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "File list output (from ls -F):"
          echo "$FILES"

      - name: Generate HTML List and Update Index
        run: |
          FILE_LIST="${{ steps.list_files.outputs.files_output }}"
          echo "FILE_LIST content: $FILE_LIST"
          HTML_LIST=""
          IFS=$'\n' read -r -d '' -a FILES_ARRAY <<< "$FILE_LIST"
          for file in "${FILES_ARRAY[@]}"; do
            if [[ "$file" != "index.html" && "$file" != ".github" ]]; then
              FILENAME=$(basename "$file")
              HTML_LIST+="<li><a href=\"./$FILENAME\">$FILENAME</a></li>"
            fi
          done

          echo "HTML_LIST content: $HTML_LIST"

          # --- Debug: Print index.html content BEFORE replacement ---
          echo "index.html content BEFORE replacement:"
          cat index.html

          # Replace placeholder in index.html with the generated list
          sed -i "s|<!-- TOOL_LIST_HERE -->|$HTML_LIST|" index.html || true # Added || true for error robustness
          echo "index.html after TOOL_LIST_HERE replacement:"
          cat index.html

          # Update title tag
          sed -i "s|<title>CODEV.ID \\| Jasa Buat Website Professional #1</title>|<title>Tools</title>|" index.html || true # Added || true for error robustness
          echo "index.html after title replacement:"
          cat index.html
          # --- Debug: Print index.html content AFTER replacement ---
          echo "index.html content AFTER replacements:"
          cat index.html


      - name: Commit and Push changes
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push updated index.html (Conditional)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"

          # Check if there are any changes to commit
          if ! git diff --quiet --exit-code index.html; then
            echo "Changes detected in index.html, committing..."
            git add index.html
            git commit -m "feat: Update tools index.html with file list"
            git push origin main
          else
            echo "No changes in index.html, skipping commit and push."
          fi
